language: go
sudo: false

go:
    - '1.9'
    - '1.10'
    - '1.11'

install:
    - go get -u golang.org/x/lint/golint
    - go get -u github.com/mattn/goveralls

script:
    - make && env IS_TRAVIS=1 make check
after_success:
    - goveralls -coverprofile=test/cov.cov -service=travis-ci
