language: go
sudo: false

go:
    - 1.5

before_install:
    - mkdir -p build/deps
    - git clone --branch=master https://github.com/holocm/holo.git build/deps/holo
    - make -C build/deps/holo build/holo
    - cp build/deps/holo/src/holo-test build/deps/holo/build/holo-test

install:
    - go get -u github.com/golang/lint/golint
    - go get -u github.com/GeertJohan/fgt

script:
    - make && env PATH=$PWD/build/deps/holo/build:$PATH make check
    - fgt gofmt -l $(find src -name \*.go)
    - fgt find src -type d -exec golint {} \;
