language: go
sudo: false

go:
    - 1.5

before_install:
    # TODO change this to the stable branch when there is one
    - mkdir -p build/deps
    - git clone --branch=v1.0-beta.2 https://github.com/holocm/holo.git build/deps/holo
    - make -C build/deps/holo build/holo
    - cp build/deps/holo/src/holo-test build/deps/holo/build/holo-test

script:
    - make && env PATH=$PWD/build/deps/holo/build:$PATH make check
